# Resource quotas for STOCKER Pro API
# These quotas ensure proper resource allocation and prevent resource exhaustion

apiVersion: v1
kind: ResourceQuota
metadata:
  name: stocker-resource-quota
spec:
  hard:
    # Compute resource limits
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    
    # Storage resource limits
    requests.storage: 100Gi
    persistentvolumeclaims: 10
    
    # Object count limits
    pods: 30
    services: 15
    configmaps: 20
    secrets: 20
    services.nodeports: 5
---
apiVersion: v1
kind: LimitRange
metadata:
  name: stocker-limit-range
spec:
  limits:
  - type: Container
    default:
      cpu: 300m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: 2
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi
  - type: PersistentVolumeClaim
    max:
      storage: 20Gi
    min:
      storage: 1Gi
