apiVersion: v1
kind: Secret
metadata:
  name: stocker-secrets
  labels:
    app: stocker-api
type: Opaque
data:
  # These are placeholder values that should be replaced in each environment
  # The values should be base64 encoded
  database_url: ${DATABASE_URL_BASE64}
  redis_url: ${REDIS_URL_BASE64}
  secret_key: ${SECRET_KEY_BASE64}
