apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocker-api
  labels:
    app: stocker-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stocker-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stocker-api
    spec:
      containers:
      - name: stocker-api
        image: stocker-pro-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: STOCKER_ENVIRONMENT
          value: "production"
        - name: STOCKER_LOG_LEVEL
          value: "info"
        - name: STOCKER_API_HOST
          value: "0.0.0.0"
        - name: STOCKER_API_PORT
          value: "8000"
        - name: STOCKER_API_WORKERS
          value: "2"
        - name: STOCKER_SECURITY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stocker-secrets
              key: security-secret-key
        - name: STOCKER_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: stocker-secrets
              key: database-url
        - name: STOCKER_REDIS_URL
          valueFrom:
            secretKeyRef:
              name: stocker-secrets
              key: redis-url
        - name: STOCKER_ALPHA_VANTAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: stocker-secrets
              key: alpha-vantage-api-key
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: data
          mountPath: /app/data
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: stocker-logs-pvc
      - name: data
        persistentVolumeClaim:
          claimName: stocker-data-pvc
