apiVersion: v1
kind: Secret
metadata:
  name: stocker-secrets
type: Opaque
stringData:
  security-secret-key: "your-secure-key-here"
  database-url: "postgresql://stocker:password@postgres-service:5432/stocker_db"
  redis-url: "redis://redis-service:6379/0"
  alpha-vantage-api-key: "your-alpha-vantage-api-key"

# Note: This is a template file. Do not commit the actual secrets file to version control.
# To create the actual secrets file:
# 1. Copy this file to secrets.yaml
# 2. Replace the placeholder values with your actual secrets
# 3. Apply the secrets: kubectl apply -f secrets.yaml
